version: '3'
volumes:
  pg_data:

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./smart_finance:/app
    command: python manage.py runserver 0.0.0.0:8000
