[tool.poetry]
name = "smart-finance"
version = "0.1.0"
description = ""
authors = ["R <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.5"

[tool.poetry.packages]

packages = [
    { include = "src/backend" },
    { include = "src/frontend" }
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
